[project]
name = "hawk-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mitmproxy>=11.1.3",
    "mitmproxy-macos>=0.11.5",
]

[dependency-groups]
dev = [
    "nuitka>=2.6.7",
]
